// Generated by CoffeeScript 1.6.2
(function() {
  this.song1 = new Song({
    title: 'Kashmere',
    artist: 'Zep'
  });

  this.song2 = new Song({
    title: 'Highway to Hell',
    artist: 'AcDc'
  });

  this.song3 = new Song({
    title: 'Concerto in D minor',
    artist: 'Back'
  });

  this.song4 = new Song({
    title: '5th Symphony',
    artist: 'Beethoven'
  });

  this.songs1 = new Songs([this.song1, this.song2]);

  this.songs2 = new Songs([this.song3, this.song4]);

  this.playlist1 = new Playlist({
    songs: this.songs1
  });

  this.playlist2 = new Playlist({
    songs: this.songs2
  });

  this.playlists = new Playlists([this.playlist1, this.playlist2]);

}).call(this);
