// Generated by CoffeeScript 1.6.2
(function() {
  var _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.Playlists = (function(_super) {
    __extends(Playlists, _super);

    function Playlists() {
      _ref = Playlists.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    Playlists.prototype.model = Playlist;

    Playlists.prototype.initialize = function(params) {
      return this.library = params.library;
    };

    return Playlists;

  })(Backbone.Collection);

}).call(this);
