// Generated by CoffeeScript 1.6.2
(function() {
  var _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.Playlist = (function(_super) {
    __extends(Playlist, _super);

    function Playlist() {
      _ref = Playlist.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    Playlist.prototype.initialize = function(params) {
      return this.set({
        'list': params.songs
      });
    };

    return Playlist;

  })(Backbone.Model);

}).call(this);
