// Generated by CoffeeScript 1.6.2
(function() {
  var _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.Song = (function(_super) {
    __extends(Song, _super);

    function Song() {
      _ref = Song.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    Song.prototype.initialize = function(params) {
      this.set({
        title: params.title,
        artist: params.artist
      });
      return this;
    };

    return Song;

  })(Backbone.Model);

}).call(this);
